#!/bin/sh
#notify-send -t 1200 "🎵Now Playing" "$(mocp -Q %file | cut -d'/' -f5 |sed -e "s/\b\(.\)/\u\1/g"|grep -oP '.*?(?=\.)')"

notify-send -t 1200 "🎵Now Playing" "$(mocp -Q %file | cut -c 18- | sed 's|instrumental/||g' | sed 's|art-of-rally/||g' | sed 's|Nusrat Fateh Ali Khan/||g' | sed -e "s/\b\(.\)/\u\1/g" |grep -oP '.*?(?=\.)')"


#notify-send -t 1200 "🎵Now Playing" "$(mocp -Q %file | cut -d'/' -f5 |sed -e "s/\b\(.\)/\u\1/g"|grep -oP '.*?(?=\.)')"
